export const INV_TRANS_HEADER_REPOSITORY = Symbol('INV_TRANS_HEADER_REPOSITORY');
export const INV_TRANS_NUMBER_GENERATOR = Symbol('INV_TRANS_NUMBER_GENERATOR');
export const STOCK_SERVICE = Symbol('STOCK_SERVICE');
export const ADJUST_REASON_REPOSITORY = Symbol('ADJUST_REASON_REPOSITORY');
