-- AlterTable
ALTER TABLE "ItemSKU" ADD COLUMN     "uomId" INTEGER;

-- AddForeignKey
ALTER TABLE "ItemSKU" ADD CONSTRAINT "ItemSKU_uomId_fkey" FOREIGN KEY ("uomId") REFERENCES "UOM"("id") ON DELETE SET NULL ON UPDATE CASCADE;
