export const SO_HEADER_REPOSITORY = Symbol('SO_HEADER_REPOSITORY');
export const SO_LINE_REPOSITORY = Symbol('SO_LINE_REPOSITORY');
export const SO_NUMBER_GENERATOR = Symbol('SO_NUMBER_GENERATOR');
export const EXCHANGE_RATE_SERVICE = Symbol('EXCHANGE_RATE_SERVICE');
export const ITEM_REPOSITORY = Symbol('ITEM_REPOSITORY');
